AutoAim:
  ros__parameters:
    use_visualization: true

    capturer:
      # int
      timeout_ms: 500
      # float
      exposure_us: 2000.0
      # float
      framerate: 80.0
      # float
      gain: 16.9807

      invert_image: false
      software_sync: false
      trigger_mode: false
      fixed_framerate: true

      print_loss_framerate: false
      print_loss_framerate_interval_seconds: 5

    visualization:
      framerate: 80
      monitor_host: "127.0.0.1"
      monitor_port: "5000"
      stream_type: "RTP_JEPG"
