use_visualization: true
use_painted_image: false
open_solved_pnp_visualization: true

capturer:
  show_loss_framerate: false
  show_loss_framerate_interval: 500
  reconnect_wait_interval: 100
  source: "local_video"
  hikcamera:
    # int
    timeout_ms: 500
    # float
    exposure_us: 3000.0
    # float
    framerate: 120
    # float
    gain: 16.9807

    invert_image: false
    software_sync: false
    trigger_mode: false
    fixed_framerate: true
  local_video:
    location: "/workspaces/RMCS/solve_pnp.mp4"
    loop_play: true

identifier:
  binarization_threshold: 0.5

  # openvino infer
  model_location: "yolov5.xml"
  infer_device: "AUTO"
  use_roi_segment: false
  use_corner_correction: false
  roi_rows: 640
  roi_cols: 640
  input_rows: 640
  input_cols: 640
  min_confidence: 0.5
  score_threshold: 0.7
  nms_threshold: 0.3

pose_estimator:
  camera_matrix: [2414.9359264386621, 0, 717.26243105567414, 0, 2418.0489262208148, 582.68540529942845, 0, 0, 1]
  distort_coeff: [-0.0209453389287673, 0.15028138841073832, -0.0006517722113234505, -0.0016861906197686788, 0]

  transforms:
    - parent: "imu_link"
      child: "pitch_link"
      t: [0., 0., 0.]
      q: [1., 0., 0., 0.]
    - parent: "pitch_link"
      child: "muzzle_link"
      t: [0., 0., 0.]
      q: [1., 0., 0., 0.]
    - parent: "pitch_link"
      child: "camera_link"
      t: [0., 0., 0.]
      q: [1., 0., 0., 0.]

visualization:
  framerate: 60
  monitor_host: "127.0.0.1"
  monitor_port: "5000"
  stream_type: "RTP_JEPG"
