name: Run Test

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: qzhhhi/rmcs-develop
      options: --user 0

    env:
      WS_DIR: ${{ github.workspace }}/ws
      SRC_DIR: ${{ github.workspace }}/ws/src
      TEST_ASSETS_ROOT: /tmp/auto_aim

    steps:
      - name: Checkout repository into ROS2 workspace
        uses: actions/checkout@v4
        with:
          repository: Alliance-Algorithm/rmcs_auto_aim_v2
          path: ws/src/rmcs_auto_aim_v2

      - name: Install yq dependency
        run: |
          apt-get update
          apt-get install -y yq

      - name: Download test assets
        shell: bash
        run: |
          cd "$SRC_DIR/rmcs_auto_aim_v2/test"
          TEST_ASSETS_ROOT="$TEST_ASSETS_ROOT" ./download_assets.sh

      - name: Configure test project
        shell: bash
        run: |
          source /opt/ros/jazzy/setup.bash
          cd "$SRC_DIR/rmcs_auto_aim_v2/test"
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build test project
        shell: bash
        run: |
          source /opt/ros/jazzy/setup.bash
          cd "$SRC_DIR/rmcs_auto_aim_v2/test"
          cmake --build build --parallel

      - name: Run gtests
        shell: bash
        run: |
          source /opt/ros/jazzy/setup.bash
          cd "$SRC_DIR/rmcs_auto_aim_v2/test"
          ctest --test-dir build --output-on-failure
